### ISSUE TITLE
OS X 10.11.5 Unable to use Afloat

### ISSUE THREAD

**Issue by aviralbansal** [rwu823/afloat#26]
Executed the following command on terminal 

curl https://raw.githubusercontent.com/rwu823/afloat/master/install.sh | sh

Restarted the OS but still do not see Afloat options in Windows menu option.

**Comment by rwu823** [comment]
Did you disable `SIP`?

**Comment by lukehatfield** [comment]
Same here. Sorry, how do check/enable SIP?

**Comment by rwu823** [comment]
#15

**Comment by Lee4649** [comment]
Dear wu, the solution (#15)  works flawlessly, thx very much! (I am with OSX 10.11.5)

**Comment by chiehkuo** [comment]
After disabling SIP and then installing a bunch of things including Github, SIMBL, EasySIMBL, Afloat...despite not knowing what the hell I'm doing, Afloat suddenly showed up on under the Window menu! But now after re-enabling SIP, it seems like Afloat options are no longer available for Chrome, Microsoft Word, etc, while it's still available for some of the other apps such as OneNote, Spotify (which I thought didnt have the options when SIP was disabled...).....is there a way to fix this so I can get Afloat on more apps?

Thanks!

**Comment by harryfear** [comment]
Same problem as me!

 

On Fri, 24 Jun 2016 at 18:49 chiehkuo

<
mailto:chiehkuo <notifications@github.com>
> wrote:

After disabling SIP and then installing a bunch of things including Github, SIMBL, EasySIMBL, Afloat...despite not knowing what the hell I'm doing, Afloat suddenly showed up on under the Window menu! But now after re-enabling SIP, it seems like Afloat options are no longer available for Chrome, Microsoft Word, etc, while it's still available for some of the other apps such as OneNote, Spotify (which I thought didnt have the options when SIP was disabled...).....is there a way to fix this so I can get Afloat on more apps?

Thanks!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/rwu823/afloat/issues/26#issuecomment-228413904
, or
https://github.com/notifications/unsubscribe/AA3ZVOsBQL0FJqD_3ARBZCZG2GcljYGHks5qPBi6gaJpZM4Iteru
.

https://github.com/rwu823/afloat/issues/26#issuecomment-228413904
