### ISSUE TITLE
Disabling SIP then reinabiling SIP

### ISSUE THREAD

**Issue by taryngabbert** [rwu823/afloat#27]
I disabled my SIP upon restart and Afloat worked perfectly. I've done this once before with Bartender, but I was able to reenable my SIP after install/ 

Is there a way I can reenable my SIP so Afloat will still work ? As it is currently not with my SIP enabled.

Thank you!

**Comment by insasquatchcountry** [comment]
The access needed to implement this kind of system-wide window augmentation requires [SIP](https://support.apple.com/en-us/HT204899) to be disabled in order to allow Afloat to run with the proper permissions of system libraries. In disabling Apples ‘rootless’ security protocol, you _may_ open your system up to exploitation. The SIP [Wikipedia](https://en.wikipedia.org/wiki/System_Integrity_Protection) page suggests one could minimize exposure by maintaining a separate Administrator account, isolating root access should that user account be compromised. 

In disabling SIP, you break Apples sandbox. If you don't mind having to switch user for Admin priveleges, you can essentially build your own layer of 'rootless'. I currently just use a firewall, disable all sharing & incoming connections, and use FileVault’s encryption.

What kind of content are you hoping to -float?

 [Helium](https://itunes.apple.com/us/app/helium/id1054607607) is an excellent App Store alternative for playing YouTube videos.
