### ISSUE TITLE
Afloat appears to be not working in 10.12 Sierra

### ISSUE THREAD

**Issue by jonmaustin** [rwu823/afloat#30]
While my level of technical skill is low, I have been using Afloat in OSX 10.11 but it appears to have been disabled or deleted since the upgrade to 10.12. I went through the steps outlined and verified the SIP was disabled (it had apparently remained disabled as the status query returned "disabled" on the restart into recovery), but the menu items do not show up in the "Window" menu in a number of third-party apps such as Chrome, Airmail, Snagit, Excel, Word that had previously displayed the items.

Any suggestions or insights are most welcome. I don't use the functionality daily but it is very handed when needed.

Thank you.

**Comment by sahin** [comment]
+1

**Comment by d-robin** [comment]
Thanks for the nice app. I hope you find some time to work on Sierra compatibility.

**Comment by vfonic** [comment]
👍

**Comment by liudanking** [comment]
+1

**Comment by rwu823** [comment]
I intend to upgrade to 10.12 Sierra recently.

**Comment by YewOw** [comment]
Manage to make it work with Sierra using mySIMBL. https://github.com/w0lfschild/mySIMBL
You have to deactivate Systems Integrity Protection to install that. Full instructions are given when you launch mySIMBL.

Another useful tidbit - The only browser that seems to work with it is Opera; tested Google Chrome, Safari, and Firefox.

**Comment by seanferd** [comment]
+1 for not working on 10.12. 

YewOw, your step didn't work for me either.

**Comment by raybero** [comment]
When running SIMBL Agent 0.9.9 I got an abort and error message indicating that garbage collection was no longer available in 10.12. I recompiled SIMBL 0.9.9 and AFloat works again. I've let Mike Solomon know so that maybe he can put a link up to newly compiled SIMBL 0.9.9 to get around this problem.

**Comment by seanferd** [comment]
Ok, after looking at this again, it does appear to work fine - just not for most windows. The only one I reliably see it affecting is the Terminal. Which is great, but I would like it to work with many others as well.

**Comment by thiagoveloso** [comment]
Thanks for sharing this application. It works flawless on Sierra (10.12.1) for nearly all windows. However, I just used your afloat bundle, not SIMBL. Instead, the SIMBL application I opted for was *mySIMBL* at https://github.com/w0lfschild/mySIMBL

**Comment by liudanking** [comment]
@thiagoveloso I have upgraded to 10.12.1. And mySIMBL and Afloat(2.4) are reinstalled. But it still did NOT work for iTerm2. Do you meet the same situation?

**Comment by thiagoveloso** [comment]
@liudanking I did not. In order to get it working, I just rebooted in recovery mode and disabled SIP. Then, rebooted to a regular boot and installed mySIMBL and Afloat from within. Last, I rebooted again in recovery mode to re-enable SIP. It has been working fine since then, except for a issue with The Unarchiver. Did you try disabling SIP? That might be a crucial step.

**Comment by liudanking** [comment]
@thiagoveloso I followed you instruction (But I did not re-enable SIP after re-install mySIMBL and Afloat, because xtrafinder need SIP disabled).

The good news is that, iterm2 works with Afloat now.

The bad news is, I need to click `inject into running applications` in mySIMBL to make iterm2 works with Afloat.

**Comment by liudanking** [comment]
@thiagoveloso After I add SIMBLAgent in login items, all works now. Thanks.

**Comment by thiagoveloso** [comment]
@liudanking cool, I'm glad it worked. Did you try using The Unarchiver with Afloat enabled? It fails here: instead of unzipping the file, it brings the settings window...

**Comment by liudanking** [comment]
@thiagoveloso yes, I meet the same problem. Currently, I use `Archive Utility` to work around.

**Comment by rwu823** [comment]
@everyone

I pushed the solution for macOS Sierra
https://github.com/rwu823/afloat#macos-sierra-solution

**Comment by HatBuddy** [comment]
I've added mySIMBL to log in items, but I still need to manually press "inject into running applications" every time I turn my mac on otherwise it doesn't work. Is there a fix to this? 
Running 10.12.1

**Comment by sadiangabay** [comment]
@rwu823 still not working after using macos-sierra-solution

**Comment by brock** [comment]
As of today on Sierra 10.12.3, this only worked for me by manually installing [mySIMBL](https://github.com/w0lfschild/mySIMBL)
